#!/bin/bash
echo "looking for java..."
if [ -e tina/java ]
  then
    echo "found java!"
  else
    wget http://dl.dropbox.com/u/122451/static/tina/java/java-x86_64.tar.gz
    tar xf java-x86_64.tar.gz
    mv java tina/java
    if [ -e tina/java ];
      then
        rm java-x86_64.tar.gz
      else
        echo "couldn't extract java, please do it manually"
    fi
fi

if [ -e viz/dist/tinaviz.jar ]
  then
    cp -R viz/dist/tinaviz.jar tina/chrome/content/applet/
fi

#if [ ! -f TinasoftPytextminer ]
#  then
#    cp -R ../TinasoftPytextminer/ .
#fi


echo "starting tinasoft desktop..."
#echo $LD_LIBRARY_PATH
cd tina
./tina &
echo "starting tinasoft http server..."
cd ../TinasoftPytextminer
python httpserver.py
