#!/bin/bash
# we also want to reuse some GUI components (JS and CSS)
# (tinaviz will be an undirect dependency)
echo "copying latest version of tinaweb (js and css)"
if [ -e ../tinaweb/html ]
   then
   rm -rf static/tinaweb
   cp -Rf ../tinaweb/html static/tinaweb
fi

