#!/bin/bash
# we also want to reuse some GUI components (JS and CSS)
# (tinaviz will be an undirect dependency)
echo "copying latest version of tinaweb (js and css)"
if [ -e ../tinaweb/html ]
   then
   rm -rf tina/chrome/content/tinaweb
   cp -Rf ../tinaweb/html tina/chrome/content/tinaweb
fi

