#!/bin/bash
# we also want to reuse some GUI components (JS and CSS)
# (tinaviz will be an undirect dependency)
echo "copying latest version"
if [ -e ../TinasoftPytextminer ]
   then
   rm -Rf TinasoftPytextminer
fi
cp -RLf ../TinasoftPytextminer .
rm -rf TinasoftPytextminer/db
rm -rf TinasoftPytextminer/user
rm -rf TinasoftPytextminer/log
rm -rf TinasoftPytextminer/source_files
rm -rf TinasoftPytextminer/build
rm -rf TinasoftPytextminer/scripts
rm -rf TinasoftPytextminer/input
rm -rf TinasoftPytextminer/output
rm -rf TinasoftPytextminer/tests
