# tinasoft.TinaApp configuration (YAML format)
---
# TinaApp main params
locale: ''
storage: "tinabsddb://tinasoft.bsddb"
index: 'index\'
dbenv: 'db\'
log: 'log\tinasoft.log'
stopwords: 'shared\stopwords\en.txt'
user: 'user\'
template: 'shared\gexf\gexf.template'
