#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "nsIURI.idl"

[scriptable, uuid(d90c75e0-e2e2-4e67-baf7-2553930f3ba7)]
interface ITinasoft : nsISupports {
    // Running means the operation has started and is working to complete
    // it's tasks.
    const long STATUS_RUNNING = 0;
    // status can be one of the states above
    attribute long status;
    // Extraction task
    wstring runImportFile(
        in wstring filePath,
        in wstring configFile,
        in wstring corpora_id,
        in boolean index,
        in wstring fileFormat,
        in boolean overwrite
    );
    // Export an extraction session
    wstring runExportCorpora(
        in wstring periods,
        in wstring corpora_id,
        in wstring exportPath,
        in wstring whitelistPath,
        in wstring userfiltersPath
    );
    // import a whitelist and writes cooc matrix
    wstring runProcessCooc(
        in wstring whitelistPath,
        in wstring corpora_id,
        in wstring periods,
        in wstring userfiltersPath
    );
    // export a cooc matrix to text file
    wstring runExportCoocMatrix();

    // export a gexf graph
    wstring runExportGraph(
        in wstring corpora_id,
        in wstring periods,
        in wstring threshold,
        in wstring whitelistPath
    );
    // file system file functions
    wstring walkGraphPath(
        in wstring corpora_id
    );

    // database read access
    wstring listCorpora();
    wstring getCorpora(in wstring str);
    wstring getCorpus(in wstring str);
    wstring getDocument(in wstring str);
    wstring getNGram(in wstring str);
    // logs the python env
    void pythonEnv();
};

[scriptable, uuid(efa88a1b-34f0-48b1-8e11-f0e5b6eb32bf)]
interface koIAsyncCallback: nsISupports {
    // Results for the callback function call
    const long RESULT_SUCCESSFUL = 0;
    const long RESULT_STOPPED = 1;
    const long RESULT_ERROR = 2;
    // result must be one of the values above
    //   successful - data contains the operation return data
    //   stopped - cancelled before operation could finish, data may be null
    //   error? use data to pass back an error message?
    void callback(in wstring filepath, out nsIURI uri);
};
